version: '3'
services:
    beast_client:
        image: beast-poc
        hostname: beast-client
        tty: true
        depends_on:
            - "beast_server"
        networks:
            beast_poc:
                ipv4_address: 10.9.0.2
        command: bash -c "sleep 3 &&
                python /usr/src/app/client.py"
    beast_server:
        build: .
        image: beast-poc
        ports:
            - 443:443
        hostname: beast-server
        tty: true
        networks:
            beast_poc:
                ipv4_address: 10.9.0.3
        command: bash -c "python /usr/src/app/server.py"
networks:
    beast_poc:
        name: beast_poc
        ipam:
            config:
                - subnet: 10.9.0.0/24
