version: '3'
services:
    beast_client:
        image: selenium/standalone-firefox:4.0.0
        ports:
            - 4444:4444
            - 7900:5900
        hostname: beast-client
        networks:
            - beast_poc
    beast_server:
        build: .
        ports:
            - 443:443
        volumes:
            - ./www:/var/www/html
        hostname: beast-server
        networks:
            - beast_poc
networks:
    beast_poc:
